APP_NAME = "mc33 str Ferlo"
APP_VERSION = "0.2.0"
APP_TITLE = "ANÁLISIS ESTERILIZACION FERLO" 

WINDOW_MIN_WIDTH = 1100
WINDOW_MIN_HEIGHT = 700

SIDEBAR_WIDTH = 200

MODAL_MIN_WIDTH = 400
MODAL_MIN_HEIGHT = 400
